filter:
  excluded_paths:
    - 'l10n/*'
    - 'js/vendor/*'

imports:
  - javascript
  - php

tools:
  external_code_coverage:
    timeout: 60

build:
  tests:
    override:
      -  jshint-run --config js/.jshintrc
