filter:
  excluded_paths:
    - 'l10n/*'

imports:
  - javascript
  - php

tools:
  external_code_coverage:
    timeout: 60

build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
          - jshint-run --config .jshintrc
