name: Missing bug template

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is marked as stale, because the necessary template
          is skipped or filled out insufficently. We cannot help without proper information.
          This issue will be closed in 5 days, unless the needed information will be added.'
        any-of-issue-labels: 'Template missing'
        labels-to-remove-when-unstale: 'Template missing'
        stale-issue-label: 'stale'
        days-before-stale: 1
        days-before-close: 5
