name: Publish beta release

on: 
  push:
    tags:
      v*-beta*

jobs:
  checkout:
    runs-on: ubuntu-latest
    name: Beta release
    steps:
    - uses: actions/checkout@v2
    - name: Check correct app version
      id: appinfo
      uses: ./.github/actions/get-polls-version

    - name: Setup node
      if: success()
      uses: ./.github/actions/setup-node

    - name: Setup composer and PHP
      if: success()
      uses: ./.github/actions/setup-composer
      with:
        mode: production
        php-tools: composer

    - name: build
      run: npm run build --if-present

    - name: Make appstore package
      if: success()
      run: make package

    - name: rename package
      if: success()
      run: mv build/artifacts/appstore/polls.tar.gz build/artifacts/appstore/polls-${{ steps.appinfo.outputs.app-version }}.tar.gz

    - name: create zip archive from sources
      if: success()
      run: |
        pushd build/source
        zip -r ../artifacts/appstore/polls-${{ steps.appinfo.outputs.app-version }}.zip *
        popd

    - name: Publish beta release
      if: success()
      uses: softprops/action-gh-release@v1
      with: 
        prerelease: true
        draft: false
        generate_release_notes: true
        files: |
          build/artifacts/appstore/polls-${{ steps.appinfo.outputs.app-version }}.tar.gz
          build/artifacts/appstore/polls-${{ steps.appinfo.outputs.app-version }}.zip
