name: Mark stale issues

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is marked as stale, because it had no activity in the last 30 days. It will be closed in 5 days.'
        stale-issue-label: 'stale'
        exempt-issue-labels: 'enhancement,bug,investigate,UX'
        exempt-pr-labels: 'enhancement,bug'
        exempt-all-milestones: true
        days-before-stale: 30
        days-before-close: 5
        days-before-pr-close: 180
        exempt-draft-pr: true
