name: psalm

on:
  pull_request:
  push:
    branches:
      - master
      - stable*

jobs:
  psalm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ocp-version: [ 'dev-master', 'dev-stable21' ]
        php-versions: ['7.4', '8.0']

    name: psalm php${{ matrix.php-versions}} ${{ matrix.ocp-version }}

    steps:
      - uses: actions/checkout@master

      - name: Setup composer and PHP
        uses: ./.github/actions/setup-composer
        with:
          php-version: ${{ matrix.php-versions }}
          php-tools: composer, psalm

      - name: Install Nextcloud API
        run: composer require --dev christophwurst/nextcloud:${{ matrix.ocp-version }}

      - name: Run coding standards check
        run: composer run psalm
